package io.kodlama.Utils.Controls.Mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.8.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface TQHIServiceEvents
{
    void Starting();
    void Completed(TQHOperationResult result);
}
