package io.kodlama.Utils.Controls.Mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.11.8.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public class TQHOperationResult< T>
{
    
    public java.lang.Exception Exception;
    
    public T Result;
    
    public java.lang.Object Tag;
    
    public java.lang.String MethodName;
}
